language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

dist:
  - xenial

addons:
  apt:
    packages:
      - cmake
      - gperf
      - libreadline-dev
      - libssl-dev
      - libncurses-dev
  homebrew:
    packages:
      - gperf
      - cmake
      - openssl
      - ncurses

#install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew bundle; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make

