language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

dist:
  - xenial

osx_image:
  - xcode11

addons:
  apt:
    packages:
      - cmake
      - gperf
      - libreadline-dev
      - libssl-dev
      - libncurses-dev
  homebrew:
    packages:
      - gperf
      - cmake
      - openssl
      - ncurses
#    update: true

script:
  - brew --version
  - mkdir -p build
  - cd build
  - cmake ..
  - make

